DROP TABLE IF EXISTS "Graphs"  CASCADE;
DROP TABLE IF EXISTS "Global_Interdependency" CASCADE;
DROP TABLE IF EXISTS "Interdependency"  CASCADE;
DROP TABLE IF EXISTS "Interdependency_Edges"  CASCADE;
DROP TABLE IF EXISTS "Nodes" CASCADE;
DROP TABLE IF EXISTS "Edges" CASCADE;
DROP TABLE IF EXISTS "Edge_Geometry" CASCADE;